name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch: # Manual button bhi jodd diya h

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📂 Checkout Code
        uses: actions/checkout@v4

      - name: 🟢 Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin' # Ye line add kar di, error khatam!
          cache: gradle

      - name: 🛠️ Grant execute permission
        run: chmod +x gradlew

      - name: 🚀 Build Debug APK (Quiet Mode)
        # 'build' ki jagah 'assembleDebug' fast hota h
        # --quiet se logs chote aayenge
        run: ./gradlew clean assembleDebug --quiet --no-daemon

      - name: ✅ Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AyushBrowser-CI
          path: app/build/outputs/apk/debug/*.apk
          retention-days: 5
          
